import sys

with open('src/App.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = '              {/* \u2500\u2500 STATUS BANNER \u2500\u2500 */}'
end_marker = '            </motion.div>'

idx_start = content.find(start_marker)
idx_end = content.find(end_marker, idx_start)

print(f'Replacing from {idx_start} to {idx_end}')
print(f'Replacing {idx_end - idx_start} chars')

new_dashboard = (
    "              {/* \u2500\u2500 STATUS ROW \u2500\u2500 */}\n"
    "              <div style={{ display: 'flex', gap: '10px', alignItems: 'center', padding: '10px 16px', background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '10px' }}>\n"
    "                <div style={{ display: 'flex', alignItems: 'center', gap: '7px', flex: 1 }}>\n"
    '                  <div style={{ width: \'6px\', height: \'6px\', borderRadius: \'50%\', background: \'#22c55e\', flexShrink: 0 }} className="pulse-slow" />\n'
    "                  <span style={{ fontSize: '0.73rem', fontWeight: 600, color: 'rgba(255,255,255,0.7)' }}>Operational</span>\n"
    "                  {lastSyncTime && <span style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.3)' }}>\u00b7 Last sync {lastSyncTime}</span>}\n"
    "                </div>\n"
    "                <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>\n"
    "                  <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>\n"
    '                    <ShieldCheck size={12} color="rgba(255,255,255,0.3)" />\n'
    "                    <span style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.4)', fontWeight: 500 }}>Safe mode</span>\n"
    "                    <span style={{ fontSize: '0.68rem', color: '#22c55e', fontWeight: 600 }}>on</span>\n"
    "                  </div>\n"
    "                  <button onClick={fetchStats} style={{ display: 'flex', alignItems: 'center', gap: '5px', background: 'rgba(155,77,255,0.1)', border: '1px solid rgba(155,77,255,0.2)', borderRadius: '6px', padding: '4px 10px', color: 'rgba(155,77,255,0.8)', fontSize: '0.68rem', fontWeight: 600, cursor: 'pointer' }}\n"
    "                    onMouseEnter={e => { (e.currentTarget as HTMLElement).style.background = 'rgba(155,77,255,0.18)'; }}\n"
    "                    onMouseLeave={e => { (e.currentTarget as HTMLElement).style.background = 'rgba(155,77,255,0.1)'; }}>\n"
    "                    <RefreshCw size={11} /> Refresh\n"
    "                  </button>\n"
    "                </div>\n"
    "              </div>\n"
    "\n"
    "              {/* \u2500\u2500 KPI GRID \u2500\u2500 */}\n"
    "              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '10px' }}>\n"
    "                {[\n"
    "                  { label: 'Brain Model', value: activeDirector.startsWith('ollama:') ? shortModelName(activeDirector.slice(7)) : activeDirector, sub: `${(tokenUsage[activeDirector] || 0).toLocaleString()} tokens` },\n"
    "                  { label: 'Coder Engine', value: activeEngine.startsWith('ollama:') ? shortModelName(activeEngine.slice(7)) : activeEngine === 'imi-core' ? 'IMI-Core' : activeEngine, sub: `${(tokenUsage[activeEngine] || 0).toLocaleString()} tokens` },\n"
    "                  { label: 'Project Files', value: stats.fileCount || '\u2014', sub: `${stats.sizeMB || '0'} MB on disk` },\n"
    "                  { label: 'Free Memory', value: stats.freeMem || '\u2014', sub: `${usage.threads || 0} threads \u00b7 load ${usage.load || '0'}` },\n"
    "                ].map((kpi, i) => (\n"
    "                  <div key={i} style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '10px', padding: '16px 18px' }}>\n"
    "                    <div style={{ fontSize: '0.65rem', fontWeight: 500, color: 'rgba(255,255,255,0.38)', marginBottom: '8px', letterSpacing: '0' }}>{kpi.label}</div>\n"
    "                    <div style={{ fontSize: '1.15rem', fontWeight: 700, color: '#fff', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', marginBottom: '4px' }}>{kpi.value}</div>\n"
    "                    <div style={{ fontSize: '0.65rem', color: 'rgba(255,255,255,0.3)', fontWeight: 400 }}>{kpi.sub}</div>\n"
    "                  </div>\n"
    "                ))}\n"
    "              </div>\n"
    "\n"
    "              {/* \u2500\u2500 MAIN BODY \u2500\u2500 */}\n"
    "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 300px', gap: '10px' }}>\n"
    "\n"
    "                {/* Engine Status */}\n"
    "                <div style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', padding: '22px 24px' }}>\n"
    "                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px' }}>\n"
    "                    <div>\n"
    "                      <div style={{ fontSize: '0.65rem', fontWeight: 500, color: 'rgba(255,255,255,0.35)', marginBottom: '6px' }}>Active Pipeline</div>\n"
    "                      <div style={{ fontSize: '1.35rem', fontWeight: 700, letterSpacing: '-0.02em', display: 'flex', alignItems: 'center', gap: '10px' }}>\n"
    "                        <span>{activeDirector.startsWith('ollama:') ? shortModelName(activeDirector.slice(7)) : activeDirector}</span>\n"
    "                        <span style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.25)', fontWeight: 400 }}>\u2192</span>\n"
    "                        <span style={{ color: 'rgba(155,77,255,0.9)' }}>{activeEngine.startsWith('ollama:') ? shortModelName(activeEngine.slice(7)) : activeEngine === 'imi-core' ? 'IMI-Core' : activeEngine}</span>\n"
    "                      </div>\n"
    "                    </div>\n"
    "                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '5px 10px', background: 'rgba(34,197,94,0.08)', border: '1px solid rgba(34,197,94,0.18)', borderRadius: '6px' }}>\n"
    '                      <div style={{ width: \'5px\', height: \'5px\', borderRadius: \'50%\', background: \'#22c55e\' }} className="pulse-slow" />\n'
    "                      <span style={{ fontSize: '0.65rem', fontWeight: 600, color: '#22c55e' }}>Live</span>\n"
    "                    </div>\n"
    "                  </div>\n"
    "\n"
    "                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px' }}>\n"
    "                    {[\n"
    "                      { label: 'Bridge Mode', value: activeEngine === 'jules' ? 'Cloud' : 'Local', ok: true },\n"
    "                      { label: 'Session Type', value: activeEngine === 'jules' ? 'Cloud Context' : 'Heartbeat', ok: true },\n"
    "                      { label: 'Latency', value: activeEngine === 'jules' ? '~450ms' : '< 1ms', ok: activeEngine !== 'jules' },\n"
    "                      { label: 'Skills', value: `${skills.length} loaded`, ok: skills.length > 0 },\n"
    "                      { label: 'MCP Servers', value: `${mcpServers.filter(s => s.status === 'online').length} / ${mcpServers.length} online`, ok: mcpServers.some(s => s.status === 'online') },\n"
    "                      { label: 'Snapshot', value: lastSnapshot ? 'Loaded' : 'None', ok: !!lastSnapshot },\n"
    "                    ].map((item, i) => (\n"
    "                      <div key={i} style={{ background: 'rgba(255,255,255,0.02)', borderRadius: '8px', padding: '11px 14px', border: '1px solid rgba(255,255,255,0.05)' }}>\n"
    "                        <div style={{ fontSize: '0.6rem', fontWeight: 500, color: 'rgba(255,255,255,0.3)', marginBottom: '5px' }}>{item.label}</div>\n"
    "                        <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>\n"
    "                          <div style={{ width: '4px', height: '4px', borderRadius: '50%', background: item.ok ? '#22c55e' : '#f87171', flexShrink: 0 }} />\n"
    "                          <span style={{ fontSize: '0.78rem', fontWeight: 600, color: item.ok ? 'rgba(255,255,255,0.85)' : '#fca5a5' }}>{item.value}</span>\n"
    "                        </div>\n"
    "                      </div>\n"
    "                    ))}\n"
    "                  </div>\n"
    "                </div>\n"
    "\n"
    "                {/* Resources */}\n"
    "                <div style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', padding: '22px', display: 'flex', flexDirection: 'column', gap: '14px' }}>\n"
    "                  <div style={{ fontSize: '0.65rem', fontWeight: 500, color: 'rgba(255,255,255,0.35)' }}>Resources</div>\n"
    "\n"
    "                  {[\n"
    "                    { label: 'CPU', value: Number(usage.cpu) || 0, color: '#60a5fa' },\n"
    "                    { label: 'RAM', value: Number(usage.ram) || 0, color: '#a78bfa' },\n"
    "                    { label: 'Skill hit rate', value: skillEfficiency || 0, color: '#22c55e' },\n"
    "                  ].map((m, i) => (\n"
    "                    <div key={i}>\n"
    "                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '5px' }}>\n"
    "                        <span style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.45)', fontWeight: 500 }}>{m.label}</span>\n"
    "                        <span style={{ fontSize: '0.68rem', fontWeight: 600, color: 'rgba(255,255,255,0.7)' }}>{m.value}%</span>\n"
    "                      </div>\n"
    "                      <div style={{ height: '3px', background: 'rgba(255,255,255,0.06)', borderRadius: '99px', overflow: 'hidden' }}>\n"
    "                        <div style={{ height: '100%', width: `${Math.min(m.value, 100)}%`, background: m.color, borderRadius: '99px', transition: 'width 0.8s ease' }} />\n"
    "                      </div>\n"
    "                    </div>\n"
    "                  ))}\n"
    "\n"
    "                  <div style={{ height: '1px', background: 'rgba(255,255,255,0.05)', margin: '2px 0' }} />\n"
    "\n"
    "                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>\n"
    "                    {[\n"
    "                      { label: 'Platform', value: stats.platform || '\u2014' },\n"
    "                      { label: 'Threads', value: String(usage.threads || '\u2014') },\n"
    "                      { label: 'Dirs', value: stats.dirCount || '\u2014' },\n"
    "                      { label: 'Load', value: usage.load ? `${usage.load}` : '\u2014' },\n"
    "                    ].map((s, i) => (\n"
    "                      <div key={i} style={{ background: 'rgba(255,255,255,0.02)', borderRadius: '7px', padding: '9px 11px', border: '1px solid rgba(255,255,255,0.04)' }}>\n"
    "                        <div style={{ fontSize: '0.58rem', color: 'rgba(255,255,255,0.28)', marginBottom: '2px' }}>{s.label}</div>\n"
    "                        <div style={{ fontSize: '0.78rem', fontWeight: 600, color: 'rgba(255,255,255,0.8)' }}>{s.value}</div>\n"
    "                      </div>\n"
    "                    ))}\n"
    "                  </div>\n"
    "\n"
    "                  <button onClick={fetchStats} style={{ marginTop: 'auto', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px', padding: '9px', background: 'transparent', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '8px', color: 'rgba(255,255,255,0.4)', fontWeight: 500, fontSize: '0.7rem', cursor: 'pointer', transition: 'all 0.15s' }}\n"
    "                    onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = 'rgba(155,77,255,0.3)'; (e.currentTarget as HTMLElement).style.color = 'rgba(155,77,255,0.9)'; }}\n"
    "                    onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = 'rgba(255,255,255,0.08)'; (e.currentTarget as HTMLElement).style.color = 'rgba(255,255,255,0.4)'; }}>\n"
    "                    <RefreshCw size={11} /> Rescan system\n"
    "                  </button>\n"
    "                </div>\n"
    "              </div>\n"
    "\n"
    "              {/* \u2500\u2500 BOTTOM ROW \u2500\u2500 */}\n"
    "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>\n"
    "\n"
    "                {/* Linked Services */}\n"
    "                <div style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', padding: '20px' }}>\n"
    "                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '14px' }}>\n"
    "                    <span style={{ fontSize: '0.65rem', fontWeight: 500, color: 'rgba(255,255,255,0.35)' }}>Linked Services</span>\n"
    "                    <span style={{ fontSize: '0.65rem', fontWeight: 600, color: mcpServers.filter(s => s.status === 'online').length > 0 ? '#22c55e' : 'rgba(255,255,255,0.3)' }}>\n"
    "                      {mcpServers.filter(s => s.status === 'online').length}/{mcpServers.length} online\n"
    "                    </span>\n"
    "                  </div>\n"
    "                  {mcpServers.length === 0 ? (\n"
    "                    <div style={{ padding: '20px 0', color: 'rgba(255,255,255,0.2)', fontSize: '0.75rem', textAlign: 'center' }}>No services linked</div>\n"
    "                  ) : (\n"
    "                    <div style={{ display: 'flex', flexDirection: 'column', gap: '5px', maxHeight: '160px', overflowY: 'auto' }}>\n"
    "                      {mcpServers.slice(0, 8).map((srv: any, i: number) => (\n"
    "                        <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 10px', background: 'rgba(255,255,255,0.02)', borderRadius: '7px' }}>\n"
    "                          <div style={{ width: '5px', height: '5px', borderRadius: '50%', background: srv.status === 'online' ? '#22c55e' : '#f87171', flexShrink: 0 }} />\n"
    "                          <span style={{ fontSize: '0.75rem', fontWeight: 500, color: 'rgba(255,255,255,0.65)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1 }}>{srv.name.replace(/^[\u25cf\u25cb\u2717\\s]+/, '')}</span>\n"
    "                          <span style={{ fontSize: '0.58rem', fontWeight: 600, color: srv.status === 'online' ? '#22c55e' : '#f87171', flexShrink: 0 }}>{srv.status}</span>\n"
    "                        </div>\n"
    "                      ))}\n"
    "                    </div>\n"
    "                  )}\n"
    "                  <button onClick={() => setActiveTab('settings')} style={{ marginTop: '12px', width: '100%', padding: '8px', background: 'transparent', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '8px', color: 'rgba(255,255,255,0.35)', fontSize: '0.68rem', fontWeight: 500, cursor: 'pointer', transition: 'all 0.15s' }}\n"
    "                    onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = 'rgba(155,77,255,0.25)'; (e.currentTarget as HTMLElement).style.color = 'rgba(155,77,255,0.8)'; }}\n"
    "                    onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = 'rgba(255,255,255,0.07)'; (e.currentTarget as HTMLElement).style.color = 'rgba(255,255,255,0.35)'; }}>\n"
    "                    Manage in System \u2192\n"
    "                  </button>\n"
    "                </div>\n"
    "\n"
    "                {/* Activity */}\n"
    "                <div style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', padding: '20px' }}>\n"
    "                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '14px' }}>\n"
    "                    <span style={{ fontSize: '0.65rem', fontWeight: 500, color: 'rgba(255,255,255,0.35)' }}>Recent Activity</span>\n"
    "                    <span style={{ fontSize: '0.65rem', color: 'rgba(255,255,255,0.2)' }}>{logs.length} events</span>\n"
    "                  </div>\n"
    "                  <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', maxHeight: '160px', overflowY: 'auto' }}>\n"
    "                    {[...logs].reverse().map((log: any) => {\n"
    "                      const c: Record<string, string> = { ag: 'rgba(155,77,255,0.8)', system: 'rgba(96,165,250,0.8)', error: '#f87171', success: '#22c55e' };\n"
    "                      return (\n"
    "                        <div key={log.id} style={{ display: 'flex', alignItems: 'flex-start', gap: '7px', padding: '6px 8px', background: 'rgba(255,255,255,0.015)', borderRadius: '6px' }}>\n"
    "                          <div style={{ width: '4px', height: '4px', borderRadius: '50%', background: c[log.type] || 'rgba(255,255,255,0.2)', flexShrink: 0, marginTop: '5px' }} />\n"
    "                          <span style={{ fontSize: '0.7rem', color: 'rgba(255,255,255,0.5)', lineHeight: 1.45, fontFamily: 'var(--font-mono)' }}>{log.msg}</span>\n"
    "                        </div>\n"
    "                      );\n"
    "                    })}\n"
    "                  </div>\n"
    "                  <button onClick={() => setActiveTab('command center')} style={{ marginTop: '12px', width: '100%', padding: '8px', background: 'transparent', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '8px', color: 'rgba(255,255,255,0.35)', fontSize: '0.68rem', fontWeight: 500, cursor: 'pointer', transition: 'all 0.15s' }}\n"
    "                    onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = 'rgba(96,165,250,0.25)'; (e.currentTarget as HTMLElement).style.color = 'rgba(96,165,250,0.8)'; }}\n"
    "                    onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = 'rgba(255,255,255,0.07)'; (e.currentTarget as HTMLElement).style.color = 'rgba(255,255,255,0.35)'; }}>\n"
    "                    Open Command Center \u2192\n"
    "                  </button>\n"
    "                </div>\n"
    "              </div>\n"
    "\n"
    "            </motion.div>"
)

new_content = content[:idx_start] + new_dashboard + content[idx_end + len('            </motion.div>'):]
with open('src/App.tsx', 'w', encoding='utf-8') as f:
    f.write(new_content)
print('Done! New file size:', len(new_content))
